# Site settings
title: "Intelda.ca Blog"
description: "A blog about AI, automation, and technology"
author: "Fakhri"
email: fakhri@intelda.ca
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# GitHub Pages specific
remote_theme: jekyll/minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages safe plugins
safe: true
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - about.md

# Social links
github_username: ""
linkedin_username: ""

# SEO
lang: en

# Google Analytics
google_analytics: ""

# Exclude from processing
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - .DS_Store
