# Site settings
title: "Intelda.ca Blog"
description: "A blog about AI, automation, and technology"
author: "Fakhri"
email: fakhri@intelda.ca
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Navigation
header_pages:
  - about.md

# Social links
github_username: ""
linkedin_username: ""

# SEO
lang: en

# Exclude from processing
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - .DS_Store
