# Site settings
title: "Build Local AI Agents with n8n"
description: "Learn how to build AI agents using n8n workflow automation platform and run them locally using Docker"
author: "Fakhri"
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - about.md

# Social links
github_username: ""
linkedin_username: ""

# SEO
lang: en
logo: /assets/images/logo.png

# Google Analytics
google_analytics: ""

# Exclude from processing
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
